---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "ui.fullname" . }}
  # annotations:
  #   kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: {{ .Values.ingress.class }}
  tls:
    - secretName: ui-ingress
  rules:
    - host: {{ .Release.Name }}.ui.158.160.129.214.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "ui.fullname" . }}
                port:
                  number: {{ .Values.service.externalPort }}
